version: '3'

services: 
  forum:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/var/www/html:cached
    command: apache2-foreground
    ports:
      - "80:80"
    env_file: .env
  db:
    image: postgres:12.7
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
