on:
  push:
    branches:
      - master

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy AWS Lambda
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build and zip lambda package
        uses: ./
      - name: Copy to s3
        run: aws s3 cp packerwire.zip s3://lambda-zips.peyton.dev/packerwire.zip
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Update Function Code
        run: aws lambda update-function-code --function-name packerwire --s3-bucket lambda-zips.peyton.dev --s3-key packerwire.zip --region us-east-1 --publish
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}